#!name= Vvebo 个人页修复
#!desc= 转自 @suiyuran


[Script]
Vebo-request = type=http-request,pattern=^https:\/\/api\.weibo\.cn\/2\/(users\/show\?|statuses\/user_timeline\?),requires-body=1,script-path=https://raw.githubusercontent.com/Keywos/rule/main/JS/vv.js#L0

Vvebo_response = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/profile\/statuses\/tab\?,requires-body=1,script-path=https://raw.githubusercontent.com/Keywos/rule/main/JS/vv.js#L0

[MITM]
hostname = %INSERT% api.weibo.cn